# -*- coding: utf-8 -*-
TR = {
# --- 01 cover
"كامن":"KAMIN",
"الموجود غير المكتشف":"What exists but has never been found",
"موجود. بس ما أحد شافه.":"It exists. Nobody has seen it.",
"خريطة حيّة لما تقدر المملكة تورّده.":"A live map of what Saudi Arabia can actually supply.",
"هاكاثون ابتكار · المسار الأول":"Innovate Hackathon · Track One",
# --- 02
"الافتتاحية":"Opening",
"«هل فيه مورد محلي؟»":"“Is there a local supplier?”",
"سؤال تظن إجابته سهلة، لدرجة إنك تتوقّع تلقاها بواحدة من هذي:":"A question so simple you would expect one of these to answer it:",
"هل فيه مورد محلي لصمام كروي ٢ بوصة؟":"Is there a local supplier for a 2-inch ball valve?",
"ما أقدر أجزم لك. تحتاج تتحقق من مصادر محلية مثل الغرف التجارية أو أدلة الموردين…":"I can’t say for certain. You would need to check local sources such as chambers of commerce or supplier directories…",
"يجاوبك بثقة، وما عنده بيانات المملكة.":"Answers with confidence. Has no Saudi data.",
"ملصق منتج":"Product label",
"صنع في السعودية":"Saudi Made",
"٤٠٪ قيمة مضافة محلية":"40% local value added",
"علامة على منتج، مو دليل موردين.":"A mark on a product, not a supplier directory.",
"المورّد":"Supplier",
"الفئة":"Category",
"شركة الخليج للتوريدات":"Gulf Supplies Co.",
"صمامات":"Valves",
"مؤسسة الرواد التجارية":"Al Ruwad Trading Est.",
"قطع غيار":"Spare parts",
"ما فيها إلا اللي اشترينا منهم قبل.":"Only holds who we have bought from before.",
"وفي الحقيقة؟ محد يقدر يجاوبه.":"And the truth? Nobody can answer it.",
# --- 03
"لماذا يهم":"Why it matters",
"الصندوق عنده أكثر من":"PIF has more than",
"١٥٠ شركة":"150 companies",
"تشتري كل يوم: حديد، صمامات، كابلات، كيماويات، معدات. وجزء كبير من اللي تشتريه يجي من الخارج.":"buying every day: steel, valves, cables, chemicals, equipment. A large share of it comes from abroad.",
"الحالة الثانية":"Case two",
"لسبب مؤسف":"For a sad reason",
"فيه أحد يصنعه على بُعد ساعتين، بس ماحد يدري عنه.":"Someone makes it two hours away, and nobody knows they exist.",
"الحالة الأولى":"Case one",
"لسبب وجيه":"For a good reason",
"فعلاً ماحد يصنعه محلياً.":"Genuinely nobody makes it locally.",
"وإلى الحين، محد يقدر يفرّق بينهما.":"And to this day, nobody can tell the two apart.",
# --- 04
"المشكلة، النصف الأول":"The problem, half one",
"ما نعرف إلا اللي يرفع يده":"We only know who raises their hand",
"عشان تعرف مصنع سعودي وش يقدر يورّد، لازم":"To find out what a Saudi factory can supply,",
"هو":"it",
"يقولك. فكل دليل موردين موجود هو لستة بأسماء اللي رفعوا أيديهم.":"has to tell you. Every supplier directory in existence is a list of who raised their hand.",
"تخيّل دليل هاتف ما تدخل فيه إلا إذا أرسلت نموذج.":"Imagine a phone book you only appear in if you submit a form.",
"ومين اللي يرسل نماذج؟":"And who submits forms?",
"الشركات الكبيرة اللي عندها فرق مبيعات شغلتها ترسل نماذج.":"Large companies with sales teams whose job is submitting forms.",
"أما الورشة في الخرج اللي لها عشرين سنة تصنّع قطع دقيقة؟ ما هي في الدليل. ولا بتدخل.":"The workshop in Al-Kharj that has been machining precision parts for twenty years? Not in the directory. Never will be.",
"وهي بالضبط اللي كنت تدور عليها.":"And it is exactly the one you were looking for.",
"مع إنه:":"Even though it:",
"فاز بمنافسات حكومية سابقة":"has won past government tenders",
"ومسجّل منتجاته عند وزارة الصناعة":"has its products registered with the Ministry of Industry",
"وعنده شهادات مطابقة منشورة":"has published conformity certificates",
"وسجله التجاري يقول وش نشاطه بالضبط":"has a commercial register stating exactly what it does",
"بس ما هو في لستة الموردين عندك.":"It just is not on your supplier list.",
# --- 05
"المشكلة، النصف الثاني":"The problem, half two",
"اختلاف المسمّى يصعّب المهمة":"The same item, three different names",
"أكثر من ١٥٠ شركة، وكل وحدة عندها نظام مشتريات مختلف، ولغتين، ونصوص حرة.":"More than 150 companies, each with a different procurement system, two languages, and free text.",
"شركة المحفظة «أ» &nbsp;·&nbsp; SAP MM":"Portfolio company A &nbsp;·&nbsp; SAP MM",
"شركة المحفظة «ب» &nbsp;·&nbsp; Oracle iProc":"Portfolio company B &nbsp;·&nbsp; Oracle iProc",
"شركة المحفظة «ج» &nbsp;·&nbsp; Excel":"Portfolio company C &nbsp;·&nbsp; Excel",
"رقم الطلب":"PR No.",
"البند":"Line",
"الوصف":"Description",
"الكمية":"Qty",
"التاريخ":"Date",
"صمام كروي ٢ بوصة":"صمام كروي ٢ بوصة",
"١٢ EA":"12 EA",
"٢٠٢٦-٠١-١٤":"2026-01-14",
"نفس الشي بالضبط.":"Exactly the same thing.",
"وثلاث نصوص الكمبيوتر يشوفها ما لها علاقة ببعض.":"And three strings a computer sees as unrelated.",
# --- 06
"ما الذي تغيّر":"What changed",
"البيانات موجودة ولكن":"The data exists, but it is",
"متناثرة":"scattered",
"يعني باحث شاطر يقعد بعد ظهر يوم واحد ويطلّعلك تقرير عن":"A good researcher spends one afternoon and comes back with a report on",
"مصنع واحد":"one factory",
"٦ مصادر":"6 sources",
"المصادر اللي لازم يفتحها لكل مصنع":"The sources they have to open for every single factory",
"منافسات":"Monafasat",
"ترسيات العقود الحكومية":"Government contract awards",
"ترميز · وزارة الصناعة":"Tarmeez · Ministry of Industry",
"كتالوج المنتجات الوطني":"National product catalogue",
"شهادة القيمة المضافة المحلية":"Local content certificate",
"المحتوى المحلي":"Local Content Authority",
"منهجية احتساب المحتوى المحلي":"Local content calculation methodology",
"الهيئة العامة للإحصاء":"GASTAT",
"الاستيراد حسب رمز المنتج":"Imports by product code",
"موقع الشركة والسجل":"Company site and registry",
"الكتالوج والشهادات والسجل التجاري":"Catalogue, certificates, commercial register",
# --- 07
"فلماذا ماحد سواها؟":"So why has nobody done it?",
"ماحد سواها لأنها تاخذ":"Nobody has done it because it takes",
"خمس سنوات":"five years",
"مصنع واحد يحتاج يوم كامل، و":"One factory needs a full day, and ",
"١٣ ألف مصنع":"13,000 factories",
"يحتاجون خمس سنوات.":"need five years.",
"وأول ما تخلص، تكون":"And the moment you finish, it is",
"آوت ديتد":"out of date",
"ولهذا هو مشروع استشاري بملايين الريالات، مو منتج.":"Which is why it is a multi-million riyal consulting project, not a product.",
# --- 08
"الفصل الثاني":"Chapter two",
"والحل؟":"So what is the fix?",
# --- 09
"طيب كيف نحلها؟":"So how do we solve it?",
"ببساطة.":"Simple.",
"نوظّف فريق.":"We hire a team.",
"أربعة أشخاص. وهذا وش يسوي كل واحد فيهم من ساعة ما يُرفع طلب شراء في نظام الشركة.":"Four people. Here is what each of them does the moment a purchase request is raised in a company system.",
"المنسّق":"The Coordinator",
"يفهم الطلب وينسّقه":"Understands the request and pools it",
"المحقّق":"The Detective",
"يدوّر مين يقدر يورّد":"Finds who can supply it",
"المدقّق":"The Auditor",
"يتحقق ويصنّف":"Verifies and classifies",
"المستشار":"The Advisor",
"لما ماحد يقدر":"When nobody can",
# --- 10
"الدور الأول":"Role one",
"يفهم وش الشي، وينسّق اللي يتشابه في طلب واحد":"Understands what the item is, and pools matching requests into one",
"شركة «أ»":"Company A",
"١٢ حبة":"12 units",
"شركة «ب»":"Company B",
"٤٠ حبة":"40 units",
"شركة «ج»":"Company C",
"٥ حبات":"5 units",
"HS 8481.80 &nbsp;·&nbsp; ٥٧ حبة الآن &nbsp;·&nbsp; ٤٠ ألف سنوياً بالتاريخ":"HS 8481.80 &nbsp;·&nbsp; 57 units now &nbsp;·&nbsp; 40,000 a year historically",
"طلب واحد مجمّع":"One pooled request",
"الطلب كان متفرق لأن":"The demand was scattered because",
"ماحد يقدر يشوف إنه نفس الطلب":"nobody could see it was the same request",
# --- 11
"الدور الثاني":"Role two",
"واحد لكل مورّد محتمل":"One per candidate supplier",
"الطلب المجمّع: ٤٠ ألف حبة سنوياً من تسع شركات":"Pooled demand: 40,000 units a year across nine companies",
"المُدخل":"Input",
"يقرأ مواقع الشركات، يفحص السجل التجاري، يشوف مين فاز بعقود مشابهة في منافسات، يلقى الشهادات ويقرأ الكتالوجات.":"Reads company websites, checks the commercial register, sees who won similar contracts on Monafasat, finds certificates and reads catalogues.",
"والسؤال تغيّر: مو «مين يصنع هذا؟» بل «مين يقدر يخدم هذا الحجم؟» وهذا يفتح موردين ما كان طلب شركة وحدة يبررهم.":"And the question changes: not “who makes this?” but “who can serve this volume?” That opens up suppliers a single company order could never justify.",
"المُخرج: مرشحون يقدرون يخدمون الحجم، ومعهم أدلتهم.":"Output: candidates who can serve the volume, each with its evidence.",
# --- 12
"الدور الثالث":"Role three",
"واحد لكل ادّعاء":"One per claim",
"المرشحون اللي لقاهم المحقّق":"The candidates the Detective found",
"ما يشطب التاجر، يصنّفه: مصنّع، أو مجمّع، أو موزّع معتمد، أو تاجر. وكل تصنيف له وزنه في المحتوى المحلي.":"It does not strike the trader out, it classifies them: manufacturer, assembler, authorised distributor, or trader. Each class carries its own weight in local content.",
"لأن التاجر المحلي برضه مورّد محلي: يوظّف سعوديين، وهامشه يبقى في البلد. محتواه أقل، مو صفر.":"Because a local trader is still a local supplier: they employ Saudis and their margin stays in the country. Lower local content, not zero.",
"المُخرج: كل مورّد بتصنيفه، ودليله، ودرجة ثقته.":"Output: every supplier with its class, its evidence, and a confidence score.",
# --- 13
"الدور الرابع":"Role four",
"واحد لكل فجوة":"One per gap",
"طلب مجمّع ماحد في المملكة يقدر يورّده":"Pooled demand nobody in the Kingdom can supply",
"الفجوة":"The gap",
"كم قيمته بالريال سنوياً؟ والأنظمة تلزم بتوطينه؟ وأي مصنع قايم يقدر يورّده لو أحد سأله؟":"What is it worth in riyals a year? Do the regulations mandate localising it? And which existing factory could supply it if anyone ever asked?",
"وهنا الفرق: الطلب صار مجمّعاً ومستقبلياً، يعني صار حجماً يبرّر الاستثمار، لا طلبية عابرة.":"And here is the difference: the demand is now pooled and forward-looking, a volume that justifies investment, not a one-off order.",
"بس ماحد سأله.":"Nobody ever asked.",
# --- 14
"أربعة أشخاص. وعشان تغطي ١٢٩٤٦ مصنع تحتاج آلاف مثلهم، وبرضه بتنتظر خمس سنوات.":"Four people. To cover 12,946 factories you would need thousands of them, and you would still wait five years.",
"بس احنا ما نوظّفهم.":"But we do not hire them.",
"نشغّلهم.":"We run them.",
"وتشغّل أربعة آلاف بنفس سهولة أربعة. والخمس سنوات تصير أقل من عشر ساعات.":"And you run four thousand as easily as four. Five years becomes under ten hours.",
"وكلاء ذكاء اصطناعي":"AI agents",
"دقيقتين للمصنع بدل يوم":"Two minutes per factory, not a day",
"٢٤ ساعة بلا توقف":"24 hours, no stopping",
"ما ينسون ولا معلومة":"They never forget a thing",
# --- 15
"ما الذي يبنونه":"What they build",
"مو إجابات. بل":"Not answers. A",
"خريطة":"map",
"وجهان: وش تقدر المملكة تورّده، ووش تشتريه المحفظة مجمّعاً":"Two faces: what the Kingdom can supply, and what the portfolio buys, pooled",
"الخريطة":"THE MAP",
"قدرات + طلب مجمّع":"Capability + pooled demand",
"مصادر عامة":"Public sources",
"سجلات · منافسات · شهادات · استيراد":"Registries · tenders · certificates · imports",
"طلبات شراء":"Purchase requests",
"من أنظمة الشركات":"From company systems",
"وكيل ذكاء اصطناعي":"AI agent",
"سجل الفجوات":"Gap register",
"قائمة موردين موثّقة":"Vetted supplier list",
"نسبة التغطية":"Coverage rate",
# --- 16
"رحلة طلب واحد":"The journey of one request",
"من طلب صغير في نظام شركة، إلى صفقة يقدر يخدمها مورّد محلي":"From a small line in one company system to a deal a local supplier can serve",
"طلب شراء":"Purchase request",
"يُرفع في نظام الشركة":"Raised in the company system",
"صمام كروي ٢ بوصة، ١٢ حبة":"2-inch ball valve, 12 units",
"يفهمه وينسّقه مع غيره":"Understands it and pools it with others",
"طلب مجمّع: ٤٠ ألف سنوياً":"Pooled demand: 40,000 a year",
"يدوّر مين يخدم الحجم":"Finds who can serve the volume",
"مرشحون ومعهم أدلتهم":"Candidates, each with evidence",
"يتحقق ويصنّف كل مرشح":"Verifies and classifies each candidate",
"مصنّع · مجمّع · موزّع · تاجر":"Manufacturer · assembler · distributor · trader",
"لما ماحد يقدر يورّده":"When nobody can supply it",
"حالة استثمارية بحجم مجمّع":"An investment case at pooled scale",
"ويبقى فيها للأبد. فالطلب اللي بعده يبدأ من خريطة أكبر، ومن طلب مجمّع أكبر.":"and stays there for good. So the next request starts from a bigger map, and bigger pooled demand.",
"بتصنيفهم وأدلتهم، وتقسيم الطلب بينهم لو ماحد يقدر يشيله كامل":"With their class and evidence, and the demand split between them if no one can carry it alone",
"طلب مجمّع بقيمته السنوية، ينتظر أول من يورّده":"Pooled demand with its annual value, waiting for the first to supply it",
"كم من إنفاق المحفظة نقدر نشتريه من هنا":"How much of the portfolio spend we can buy from here",
# --- 17
"الحساب":"The math",
"الطريقة القديمة":"The old way",
"الوقت":"Time",
"٥ سنوات":"5 years",
"أقل من ١٠ ساعات":"Under 10 hours",
"التكلفة":"Cost",
"ملايين الريالات":"Millions of riyals",
"أقل من ٤ آلاف دولار":"Under $4,000",
"الحداثة":"Freshness",
"تقرير يطلع قديم":"A report born stale",
"يحدّث نفسه":"Updates itself",
"الجزء الغالي ما كان أبداً التفكير.":"The expensive part was never the thinking.",
"كان عدد الأيام.":"It was the number of days.",
# --- 18
"مساهمة تعرف":"Musahama knows",
"مين سجّل":"who registered",
"كامن يعرف":"KAMIN knows",
"اللي ما رفع يده":"who never raised a hand",
"الأولى لستة بأسماء اللي رفعوا أيديهم. والثانية خريطة لللي موجود فعلاً، بما فيهم كل اللي ما رفع يده أبداً.":"The first is a list of names that raised their hand. The second is a map of what actually exists, including everyone who never raised theirs.",
"احنا مو بديل للمنصة. احنا الطبقة اللي تحتها.":"We are not a replacement for the platform. We are the layer underneath it.",
# --- appendix
"بدوننا":"Without us",
"كيف يُجاب السؤال اليوم":"How the question gets answered today",
"مهندس يكتبه بنص حر":"An engineer types it as free text",
"المشتري":"The buyer",
"فئة الشراء في الشركة":"The company category buyer",
"لستة الموردين المعتمدين":"The approved supplier list",
"مين اشترينا منهم قبل":"Who we have bought from before",
"قرار في دقائق":"A decision in minutes",
"من الذاكرة، مو من دليل":"From memory, not from a directory",
"النتيجة الثانية":"Outcome two",
"ما لقى اسم":"No name found",
"«ماحد يصنعه محلياً» ← استيراد، أو شراء من وكيل محلي يستورد ويبيع.":"“Nobody makes it locally” → import, or buy from a local agent who imports and resells.",
"النتيجة الأولى":"Outcome one",
"لقى اسم في لستته":"Found a name on the list",
"يرسل طلب عرض سعر لثلاثة أو خمسة من نفس اللستة.":"Sends an RFQ to three or five names from that same list.",
"و«ماحد يصنعه محلياً» مو حقيقة، بل «ماحد في لستتي».":"And “nobody makes it locally” is not a fact, it is “nobody on my list.”",
"ملحق":"Appendix",
# --- 19 team
"من نحن":"Who we are",
"ثلاثة أشخاص. ":"Three people. ",
"وآلاف الوكلاء":"Thousands of agents",
"الفريق اللي يبني كامن.":"The team building KAMIN.",
"محمد شلبي":"Mohammed Shalabi",
"علي بامعلم":"Ali Bamuallim",
"عبدالعزيز الحارثي":"Abdulaziz Al Harthi",
}
